# Setup script to install git hooks for pre-commit validation
# Run this once after cloning the repository

Write-Host "Setting up git hooks for pre-commit validation..." -ForegroundColor Cyan

$hooksDir = ".git\hooks"
$preCommitHook = "$hooksDir\pre-commit"

# Create hooks directory if it doesn't exist
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

# Copy the pre-commit hook
if (Test-Path ".\scripts\ci-local.ps1") {
    $hookContent = @"
# Pre-commit hook - runs CI checks before allowing commit
# This hook is auto-generated by setup-git-hooks.ps1

& ".\scripts\ci-local.ps1"
if (`$LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "Pre-commit checks failed. Please fix the errors before committing." -ForegroundColor Red
    Write-Host "You can bypass this hook with: git commit --no-verify" -ForegroundColor Yellow
    exit 1
}
exit 0
"@
    
    Set-Content -Path $preCommitHook -Value $hookContent
    Write-Host "✅ Pre-commit hook installed successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "The hook will now run CI checks before each commit." -ForegroundColor Yellow
    Write-Host "To bypass: git commit --no-verify" -ForegroundColor Gray
} else {
    Write-Host "❌ Error: scripts/ci-local.ps1 not found!" -ForegroundColor Red
    exit 1
}

